dependencies {
    api project(':piped-template-engine-core')

    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.3.4'
    implementation 'org.springframework:spring-webmvc:6.1.13'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.3.4'
}
